"""Original beginner bridges. Course coverage is evidence, not proof of mastery.
No private learning profile is distributed. These texts update only theory, never quizzes.
"""
GUIDES = {}

def guide(key, prerequisite, bridge, trace):
    GUIDES[key] = (prerequisite, bridge, trace)

guide('java-runtime', 'Un file sorgente contiene istruzioni che scrivi. Il processore esegue invece istruzioni macchina: serve un percorso che colleghi questi livelli.',
'''Il JDK è la distribuzione con cui sviluppi: comprende il compilatore javac, strumenti e un runtime. La JVM è il motore che esegue bytecode, una rappresentazione intermedia del programma. Un file .class contiene quel bytecode, non un processo già in esecuzione.

Prima scrivi Main.java. Poi javac controlla sintassi e tipi e produce Main.class. Quando esegui java Main, il launcher avvia il runtime, che carica e verifica le classi necessarie e cerca il metodo main. Durante l’esecuzione la JVM può interpretare istruzioni e compilare le parti frequenti in codice macchina con il JIT. Non immaginare due compilazioni integrali obbligatorie: la strategia dipende dal runtime.

Una JVM vecchia non comprende necessariamente class file nuovi. Inoltre il codice può usare API assenti nel runtime destinatario. La JVM Java SE del backend e il runtime Android non espongono automaticamente le stesse API.''',
'javac --release 17 chiede compatibilità con linguaggio e API Java 17. java Main esegue la classe senza scrivere .class. javap -c mostra il bytecode prodotto. Sono tre comandi con scopi distinti: preparazione, esecuzione e ispezione.')
guide('java-types', 'Distingui un valore come 7 da un riferimento che permette di raggiungere un oggetto.',
'Un tipo stabilisce valori e operazioni ammessi. int è un intero primitivo; Integer è un oggetto wrapper e può anche essere null. Boxing e unboxing convertono tra questi livelli, ma non li rendono identici: convertire null in int fallisce perché null non contiene alcun numero. Una conversione può anche perdere informazione quando il tipo destinatario non rappresenta il valore iniziale.',
'Segui prima i tipi degli operandi e poi il calcolo. Due interi vengono divisi come interi anche se assegni dopo il risultato a double. Un cast prima della divisione può cambiare l’operazione; un cast dopo non recupera decimali già persi. Per ogni riga scrivi mentalmente il valore calcolato prima della conversione.')
guide('java-control', 'Lo scope è l’intervallo del programma in cui il nome di una variabile è utilizzabile.',
'if sceglie un ramo, un ciclo ripete un lavoro e return termina il metodo corrente. Non leggere una condizione come una frase generica: valuta gli operandi nell’ordine previsto. && e || possono evitare la valutazione del secondo operando quando il primo basta a decidere il risultato. Questo conta se il secondo operando accede a un oggetto o esegue un’operazione con effetti.',
'Nel controllo di null verifica ordine e uso di && prima di accedere all’oggetto. Per un ciclo identifica valore iniziale, condizione e aggiornamento: così ricostruisci primo e ultimo giro senza indovinare. Una variabile dichiarata dentro un blocco non diventa automaticamente disponibile dopo la sua chiusura.')
guide('java-methods', 'Un metodo riceve argomenti e può restituire un risultato. I parametri sono variabili locali.',
'Java passa sempre valori. Per un numero, il metodo riceve una copia del numero. Per un oggetto, riceve una copia del riferimento: entrambe le variabili possono raggiungere lo stesso oggetto. Modificare quell’oggetto è diverso dal riassegnare il parametro a un altro oggetto. Questa distinzione spiega perché certe modifiche sono visibili al chiamante e altre no.',
'Segui separatamente variabile esterna e parametro. Riassegnare il parametro non cambia la variabile esterna; modificare un campo dell’oggetto condiviso può invece essere osservato. I varargs rendono comoda la chiamata ma vengono gestiti come un array. Per riconoscere un overload confronta i parametri, non soltanto il ritorno.')
guide('java-strings', 'Una variabile String contiene un riferimento a un oggetto che rappresenta testo.',
'Immutabile significa che il valore di una String già creata non viene modificato dai suoi metodi. toUpperCase o una concatenazione producono un risultato da usare o assegnare. La variabile può comunque essere riassegnata. Per i riferimenti, == verifica l’identità dell’oggetto; equals verifica l’uguaglianza secondo il contratto della classe, che per String riguarda il contenuto.',
'Osserva dove viene salvato il risultato. Ignorare la String restituita non aggiorna la variabile iniziale. StringBuilder accumula invece testo in modo mutabile e toString produce il risultato finale. I text block aiutano a scrivere testo su più righe: non cambiano il fatto che il risultato sia una String.')
guide('java-oop', 'La classe descrive un tipo di oggetto; un’istanza è un oggetto concreto costruito da quella descrizione.',
'Lo stato comprende i dati dell’oggetto e il comportamento le sue operazioni. Un costruttore deve stabilire condizioni iniziali valide. Incapsulare significa proteggere queste regole attraverso un’API: rendere i campi private non basta se ogni setter permette valori incoerenti. Un riferimento final non può essere riassegnato, ma l’oggetto raggiunto può essere ancora mutabile.',
'Counter rifiuta un valore iniziale negativo nel costruttore; increment controlla la modifica e value espone la lettura. Immagina due istanze con campi distinti. Un campo static è invece associato alla classe: prima di usarlo per dati variabili, considera chi lo condivide e quanto dura quello stato.')
guide('java-inheritance', 'Distingui il tipo dichiarato della variabile dal tipo reale dell’oggetto raggiunto.',
'L’ereditarietà permette di usare un sottotipo nel contratto del tipo base. Override ridefinisce un metodo d’istanza ereditato; il polimorfismo sceglie il comportamento in base all’oggetto reale. Overload dichiara firme differenti con lo stesso nome e viene risolto dal compilatore attraverso tipi e argomenti disponibili. Queste due scelte avvengono in momenti diversi.',
'In Animal a = new Dog(), a è dichiarata Animal ma raggiunge Dog: sound usa l’override di Dog. Non applicare questa regola ai metodi static. Cambiare solo il ritorno non crea un overload. Prima di estendere una classe, verifica una vera relazione di sottotipo e considera la composizione per il semplice riuso.')
guide('java-contracts', 'Un contratto descrive le operazioni offerte senza imporre al chiamante ogni dettaglio interno.',
'Un’interfaccia permette a classi diverse di offrire le stesse operazioni. Una classe astratta può condividere stato e implementazioni, ma non viene istanziata direttamente. La composizione costruisce comportamento collaborando con altri oggetti: è utile quando un componente ha bisogno di una capacità senza essere un sottotipo del suo fornitore.',
'Leggi prima ciò che invoca il chiamante e poi la classe concreta che lo realizza. Se cambi implementazione, il chiamante dovrebbe poter mantenere il contratto. Questo ragionamento spiega anche l’iniezione di servizi Spring attraverso interfacce. Non aggiungere un’interfaccia soltanto per aumentare il numero di file: deve rendere utile un confine.')
guide('java-equality', 'Variabili diverse possono raggiungere lo stesso oggetto o oggetti distinti che rappresentano lo stesso valore.',
'== verifica l’identità dei riferimenti. equals definisce uguaglianza logica secondo i dati scelti dalla classe. hashCode aiuta le strutture hash a cercare candidati, ma non sostituisce equals. Se due oggetti sono uguali secondo equals, devono avere lo stesso hashCode. Il contrario non è garantito: valori diversi possono produrre una collisione.',
'In HashSet e HashMap segui prima l’hash e poi il confronto. Se modifichi un campo che determina hash ed uguaglianza dopo l’inserimento, puoi non ritrovare l’oggetto nel modo atteso. Controlla che i due metodi esprimano gli stessi criteri logici; non devono per forza includere ogni campo disponibile.')
guide('java-records', 'Un tipo può rappresentare dati, una scelta finita o una famiglia controllata di comportamenti.',
'Il record genera operazioni utili per dati basati sui propri componenti. I riferimenti dei componenti sono final, ma una lista contenuta non diventa automaticamente immutabile. Un enum rappresenta costanti nominate; sealed limita quali sottotipi diretti sono ammessi. Sono strumenti distinti e vanno scelti in base al significato del modello.',
'Per il record controlla se occorre una copia difensiva di una collezione. Per l’enum ragiona sul nome della costante e non usare ordinal come identificatore persistente senza un contratto: riordinare le costanti lo cambia. Per sealed verifica quali varianti deve davvero ammettere il dominio.')
guide('java-exceptions', 'Un errore richiede una causa, un contesto e una scelta su chi possa recuperare.',
'Un’eccezione interrompe il percorso normale e risale le chiamate fino a una gestione compatibile. Le checked devono essere catturate o dichiarate; RuntimeException non ha questo obbligo. Gestire non significa nascondere con un catch vuoto. Se traduci il problema a un livello superiore, conserva la causa. File e connessioni richiedono inoltre chiusura deterministica.',
'Nel try-with-resources la risorsa viene acquisita nell’intestazione e chiusa anche se il corpo fallisce. Distingui l’errore principale da uno eventuale in chiusura, che può comparire tra le eccezioni soppresse. Non affidare al GC il momento in cui chiudere una risorsa esterna.')
guide('java-generics', 'Specificare il tipo degli elementi permette al compilatore di controllare inserimenti e letture.',
'List<String> esprime una lista di String e riduce i cast. List<Integer> non è un sottotipo di List<Number>: altrimenti potresti inserire Double in una lista destinata a Integer. Le wildcard controllano la flessibilità. extends aiuta a leggere valori utilizzabili come il limite superiore; super permette inserimenti compatibili ma rende la lettura meno specifica.',
'Per il parametro dell’esempio chiediti se il metodo legga elementi o li inserisca. Solo dopo usa PECS: producer extends, consumer super. La type erasure spiega limiti come new T(), ma non cancella i controlli già svolti dal compilatore. Evita raw type che spostano un errore verificabile a un cast fallito a runtime.')
guide('java-lists', 'Scegli una struttura in base a ordine, duplicati, chiavi e operazioni frequenti.',
'List conserva una sequenza con possibili duplicati; Set mantiene elementi unici secondo il proprio contratto; Map collega chiavi a valori. La complessità descrive come cresce il costo al crescere dei dati, non il tempo esatto. O(1) atteso per una ricerca hash non significa istantaneo: hash, collisioni e dimensioni reali contano.',
'Prima individua la domanda posta ai dati: ricerca per ID, posizione nella sequenza o verifica di unicità. Poi scegli la struttura e controlla l’ordine promesso. Non tutte mantengono l’inserimento. Una collezione non modificabile può comunque contenere oggetti mutabili: considera separatamente struttura e contenuto.')
guide('java-ordering', 'Confrontare per ordinare significa stabilire chi venga prima, non solo chi sia uguale.',
'Comparator restituisce un valore negativo, zero o positivo e può esprimere criteri esterni alla classe. Il contratto richiede coerenza e transitività. In strutture ordinate, zero nel confronto può far considerare equivalenti elementi che equals distingue. Ordinamento e uguaglianza devono quindi essere scelti con consapevolezza.',
'Segui criterio principale e thenComparing. Evita la sottrazione per confrontare interi, perché può produrre overflow e invertire l’ordine. Se ordini per un valore non univoco, considera uno spareggio stabile. Per una collezione immutabile chiediti anche se gli elementi siano immutabili o soltanto il contenitore.')
guide('java-lambdas', 'Un’interfaccia funzionale ha un solo metodo astratto da implementare: la lambda ne fornisce il comportamento.',
'Una lambda non è un thread e non parte da sola. Descrive un’operazione che un’API invocherà. Predicate riceve un valore e produce booleano; Function trasforma; Consumer esegue senza risultato; Supplier produce un valore. Prima della sintassi breve, ricostruisci parametri e ritorno del contratto.',
'Nel Predicate, s è l’argomento e l’espressione verifica la validità. String::length rappresenta un metodo compatibile con la trasformazione richiesta. La cattura richiede variabili locali final o effectively final: vieta la riassegnazione, ma non rende immutabile l’oggetto raggiunto. Valuta separatamente eventuali effetti collaterali.')
guide('java-streams', 'Una collezione conserva elementi; uno Stream descrive un’elaborazione da una sorgente.',
'Leggi filter come selezione, map come trasformazione e sorted come ordinamento. Le operazioni intermedie sono lazy e la terminale avvia la traversata necessaria. Non riutilizzare uno Stream già consumato e non modificarne la sorgente durante l’elaborazione. Una pipeline leggibile rende visibili i passaggi, non soltanto il risultato finale.',
'Nell’esempio users è la sorgente, filter conserva utenti attivi, map estrae nomi e toList materializza il risultato. Stream.toList produce una lista non modificabile. Il parallelismo richiede funzioni non interferenti e riduzioni appropriate: non aggiungerlo per accelerare senza una misura e un controllo degli effetti collaterali.')
guide('java-optional', 'L’assenza di un risultato può essere prevista e dovrebbe avere un significato esplicito.',
'Optional descrive nel ritorno la possibilità di non trovare un valore. map trasforma il contenuto presente; flatMap collega un’operazione che restituisce già Optional evitando un annidamento. Non sostituisce ogni null e non giustifica get senza controllo. Se l’assenza è un errore di dominio, scegli un’eccezione adeguata.',
'Segui caso presente e assente. Con orElse l’argomento alternativo viene valutato prima della chiamata anche se non sarà usato. Con orElseGet il calcolo avviene soltanto quando serve. Il tipo finale ti aiuta a capire se una trasformazione abbia aggiunto un livello Optional involontario.')
guide('java-time', 'Data di calendario, orario locale e istante globale non rappresentano la stessa informazione.',
'LocalDate è una data senza orario; LocalDateTime contiene data e ora ma non fuso. Instant identifica un momento sulla linea temporale. ZoneId porta le regole per convertirlo in un orario locale. I cambi di ora legale possono rendere orari ambigui o inesistenti: non basta applicare sempre una differenza fissa.',
'Prima identifica se il dato sia un compleanno, un appuntamento locale o un evento avvenuto. Poi scegli il tipo. Nei test usa un Clock controllato per evitare dipendenza dall’orologio reale. Period riguarda quantità di calendario, Duration quantità temporali: osserva il significato prima di sommare.')
guide('java-io', 'I/O significa scambio di dati con risorse esterne; il programma può dover attendere.',
'Path rappresenta un percorso e non il contenuto del file. Files offre operazioni su percorsi e dati. Un charset come UTF-8 stabilisce la trasformazione tra testo e byte: lettura e scrittura incoerenti possono alterare i caratteri. File grandi possono richiedere una lettura progressiva invece di una copia completa in memoria.',
'Identifica percorso, codifica e chiusura. Nel ciclo di lettura distingui apertura del flusso e consumo dei dati. Un percorso esterno deve anche essere autorizzato: normalizzare da solo non impedisce ogni accesso fuori dalla directory consentita. Usa try-with-resources per non trattenere file aperti quando il lavoro fallisce.')
guide('java-jdbc', 'JDBC è l’API che collega Java a operazioni e risultati di un database.',
'Connection rappresenta la connessione; PreparedStatement separa SQL e valori associati ai placeholder. Questo protegge i valori parametrizzati dall’iniezione nel testo SQL, ma non permette di parametrizzare liberamente nomi di tabelle. Una transazione raggruppa operazioni da confermare con commit o annullare con rollback.',
'Segui acquisizione, preparazione, parametri, esecuzione e lettura del risultato. Se disabiliti auto-commit, gestisci anche fallimento e ripristino dello stato. Chiudi ResultSet, statement e connessione in modo deterministico. Con un pool, close normalmente restituisce la connessione al pool anziché distruggerla fisicamente.')
guide('java-memory', 'Distingui variabile, riferimento e oggetto raggiunto: non sono tre nomi della stessa cosa.',
'''Lo stack di un thread contiene frame delle chiamate ai metodi, con variabili locali e informazioni per l’esecuzione. L’heap è l’area logica condivisa da cui sono allocate istanze e array. La formula “primitive nello stack, oggetti nell’heap” è troppo assoluta: un campo int appartiene allo stato dell’oggetto e il runtime può ottimizzare allocazioni e rappresentazioni.

Il GC recupera memoria di oggetti non più raggiungibili dalle radici del runtime. Non sa se un oggetto raggiungibile sia inutile per il dominio: una lista statica che conserva dati per sempre può causare una perdita logica. Rilasciare un riferimento non obbliga una raccolta immediata. La gestione della memoria non sostituisce la chiusura esplicita di file e connessioni.''',
'Se due variabili raggiungono lo stesso oggetto, assegnare null a una lascia l’altro percorso aperto. Segui tutti i riferimenti prima di considerarlo raccoglibile. Per ricorsione, osserva la crescita dei frame: lo stack può esaurirsi anche se l’heap ha ancora spazio. Le aree logiche aiutano a capire cause diverse di errori diversi.')
guide('java-threads', 'Bastano metodi, oggetti e una lambda semplice. I lock verranno introdotti soltanto dopo il significato di esecuzione concorrente.',
'''Un processo è un programma in esecuzione con le proprie risorse. Un thread è un percorso di esecuzione al suo interno. Il main è già eseguito da un thread; chiamare un normale metodo non ne crea uno nuovo. Un thread può usare molti oggetti e chiamare molti metodi: non esiste una corrispondenza “una classe, un thread”.

Separiamo lavoro ed esecutore. Runnable è un’interfaccia con il metodo run e descrive un lavoro senza risultato restituito da quel metodo. Una lambda assegnata a Runnable prepara le istruzioni. Thread fornisce un contesto per eseguirle in un altro percorso. new Thread(task) prepara quel contesto, ma non lo avvia.

start chiede al runtime di avviare il thread, che eseguirà run mentre il chiamante può proseguire. Chiamare run direttamente è invece una normale invocazione sul thread chiamante. Perciò new Thread(task).run() non crea la concorrenza cercata. Uno stesso oggetto Thread può essere avviato una sola volta: un thread terminato non si riavvia con un secondo start.

Concorrenza significa che più lavori avanzano nello stesso intervallo; parallelismo significa esecuzione effettivamente simultanea. Anche con un solo core il sistema può alternare thread. Lo scheduler decide quando eseguire un thread disponibile: l’ordine delle stampe di una prova non è una garanzia per tutte le esecuzioni.

join fa attendere il chiamante fino alla conclusione di un altro thread. Non rende atomici tutti i dati e non chiude il thread. sleep sospende temporaneamente il thread corrente e non garantisce che un altro abbia completato il lavoro. L’interruzione è una richiesta cooperativa: il codice deve decidere come reagire e non viene automaticamente terminato con la forza.

NEW indica un Thread non avviato; RUNNABLE include disponibilità all’esecuzione ed esecuzione; BLOCKED riguarda un monitor; WAITING e TIMED_WAITING riguardano attese; TERMINATED indica conclusione. Questi stati descrivono condizioni, non promettono tempi né ordine tra lavori.''',
'Leggi prima il corpo di Runnable. La costruzione collega il lavoro al Thread; start avvia il contesto; join fa attendere il chiamante. Se join viene interrotto e non puoi propagare InterruptedException, ripristinare il flag con Thread.currentThread().interrupt() conserva il segnale per il codice superiore. Su una UI, aspettare con join sul thread principale può bloccare l’interazione: conta anche chi sta aspettando.')
guide('java-locks', 'Prima comprendi thread e stato condiviso: il problema nasce quando più percorsi accedono allo stesso dato.',
'''value++ sembra un gesto unico, ma logicamente legge, calcola e scrive. Due thread possono leggere entrambi 0, calcolare entrambi 1 e scrivere entrambi 1: due incrementi hanno prodotto un solo aumento. Questo aggiornamento perso nasce dall’interleaving, cioè dall’intreccio delle operazioni.

synchronized acquisisce il monitor di un oggetto, esegue una sezione e lo rilascia all’uscita, anche attraverso un’eccezione. Un altro thread che richiede lo stesso monitor deve aspettare. Il lock non viene rilasciato subito perché compare synchronized: protegge la sezione finché il proprietario ne esce. Il metodo d’istanza usa this; quello static usa l’oggetto Class.

Usare lo stesso lock è essenziale. Sincronizzare su oggetti distinti non coordina i thread per quel dato. Anche le letture devono rispettare la strategia di accesso. Visibilità significa che una modifica viene osservata secondo le garanzie del modello di memoria. Rilascio e successiva acquisizione dello stesso monitor stabiliscono happens-before: una relazione di ordine e visibilità, non una semplice impressione sull’orologio.

volatile può essere adatto a un flag condiviso, ma non trasforma value++ in un’operazione atomica. AtomicInteger offre incrementAndGet con un contratto atomico sul valore. Se la regola coinvolge più campi, rendere atomico ciascuno separatamente può non proteggere l’invariante complessivo.

Un deadlock nasce per esempio quando A possiede X e aspetta Y mentre B possiede Y e aspetta X. Un ordine coerente di acquisizione aiuta a prevenire quel ciclo. Prima dei lock identifica stato condiviso e operazioni indivisibili: non aggiungerli casualmente finché una prova smette di fallire.''',
'Ricostruisci prima la sequenza errata: leggi 0, leggi 0, scrivi 1, scrivi 1. Con lo stesso monitor il secondo thread entra dopo l’uscita del primo e legge il valore aggiornato. Controlla che tutti gli accessi rilevanti rispettino quel monitor. Una singola stampa corretta non prova che tutte le esecuzioni siano sicure.')
guide('java-executors', 'Prima distingui task, thread e attesa di un risultato.',
'''Executor separa il lavoro dalla politica che decide quando e dove eseguirlo. Un pool riutilizza lavoratori invece di creare un thread manuale per ogni chiamata. Questo limita una parte delle risorse, ma una coda può crescere se produci task più velocemente di quanto vengano completati.

submit può restituire Future, un oggetto che rappresenta un risultato forse non ancora disponibile. get può bloccare il chiamante. Sul thread della UI questa attesa può fermare l’interazione. Devi considerare anche fallimento, timeout, interruzione e cancellazione: una richiesta di cancellazione non garantisce l’arresto istantaneo di ogni operazione.

CompletableFuture permette di descrivere passaggi successivi. thenApply trasforma un valore; thenCompose collega una funzione che restituisce un’altra fase evitando un livello annidato. Le varianti Async hanno regole di esecuzione proprie e possono ricevere un executor; una continuazione non Async non significa “sempre su un thread nuovo”.

Asincrono non significa automaticamente più veloce o non bloccante. JDBC dentro un task continua a poter bloccare il thread che lo esegue. Scegli dimensione e coda considerando attese, calcolo e limiti esterni. Il proprietario deve gestire anche chiusura: shutdown smette di accettare nuovi lavori e avvia la chiusura ordinata, ma non afferma che tutti siano già terminati.''',
'Segui avvio, trasformazione e gestione dell’errore. Cerca ogni get o join che possa bloccare il chiamante. Se una funzione restituisce già CompletableFuture, confronta thenApply e thenCompose: il tipo finale mostra se hai creato un future annidato. Individua chi conserva l’executor e in quale momento ne gestisce la chiusura.')
guide('java-virtual', 'Studia prima thread, executor e la differenza tra calcolo CPU e attesa I/O.',
'''I virtual thread, stabili da Java 21, sono gestiti dal runtime e riducono il costo di molti lavori concorrenti, soprattutto quando attendono I/O. Restano thread: lo stato condiviso richiede le stesse garanzie. Immagina mille richieste in attesa della rete: per gran parte del tempo non eseguono calcoli. Il runtime può organizzare quei lavori su thread di supporto chiamati carrier.

Questo non aggiunge core né accelera automaticamente mille calcoli pesanti. Il modello usuale è un virtual thread per task; le risorse scarse vanno limitate separatamente. Se il database offre venti connessioni, diecimila task non creano diecimila connessioni. Considera code, timeout e limiti del servizio esterno.

Il pinning descrive casi in cui un virtual thread non libera il carrier come previsto durante certe operazioni. I dettagli dipendono dalla versione della JVM: non estendere automaticamente indicazioni Java 21 a versioni successive. ThreadLocal può moltiplicare il consumo quando ogni thread conserva dati pesanti.

Questa lezione riguarda Java SE del backend. Il fatto che l’app Android usi Java non rende tali API disponibili automaticamente su Android API 26. Versione del linguaggio e librerie del runtime sono livelli distinti.''',
'newVirtualThreadPerTaskExecutor crea un virtual thread per ogni task. Leggi il corpo del lavoro per distinguere attesa e calcolo. La gestione del ciclo di vita evita di abbandonare lavori attivi, ma non aumenta la capacità del database. Prima di usare l’esempio verifica Java 21 nel runtime destinatario.')
guide('java-reflection', 'Un’annotazione descrive metadati; un oggetto Class rappresenta un tipo a runtime.',
'Reflection permette di ispezionare classi e membri. Un framework può leggere annotazioni e applicare comportamento, ma l’annotazione non lo esegue da sola. Retention determina dove restano i metadati. Un proxy intercetta chiamate e può aggiungere lavoro prima o dopo una delega: è utile per capire transazioni e altri comportamenti trasversali.',
'Identifica chi interpreta l’annotazione. Poi segui se la chiamata passa davvero dal proxy. Una chiamata interna può evitare l’intercettazione prevista: la self-invocation Spring è un esempio. Non confondere la presenza dell’annotazione con la prova che l’infrastruttura sia attivata.')
guide('java-modules', 'Package organizza nomi; JAR archivia classi e risorse; modulo dichiara anche confini.',
'Classpath indica dove cercare classi non modulari. Module path contiene moduli nominati con dipendenze ed esportazioni. Non sono sinonimi di directory. Un modulo può contenere tipi che non offre come API pubblica: la separazione aiuta a controllare dipendenze e accessi invece di rendere disponibile ogni dettaglio interno.',
'In module-info, requires dichiara dipendenze ed exports espone un package. opens riguarda accesso riflessivo profondo e non va aggiunto indiscriminatamente. Per una classe mancante controlla artefatto, percorso e visibilità, distinguendo errore di caricamento da una dipendenza non dichiarata.')
guide('java-testing', 'Un test esegue un comportamento in condizioni controllate e verifica una promessa osservabile.',
'Il test unitario isola una responsabilità. Prepara dati, invoca il comportamento e confronta l’esito. Non dovrebbe copiare l’algoritmo, perché potrebbe ripetere lo stesso errore. Controlla tempo, casualità e dipendenze per ottenere una prova riproducibile. Un mock controlla una collaborazione ma non dimostra che una risorsa esterna reale funzioni.',
'Distingui preparazione, azione e assert. Il risultato atteso deve esprimere il contratto. Per un errore previsto verifica anche il tipo o i dettagli utili. Se il problema riguarda SQL, rete o configurazione Spring, valuta un test di integrazione invece di sostituire proprio il confine che vuoi verificare.')
guide('java-build', 'Una build può compilare, risolvere dipendenze, eseguire test e costruire un artefatto.',
'Maven e Gradle automatizzano il processo. Una dipendenza diretta viene dichiarata; una transitiva arriva attraverso un’altra libreria. La versione risolta dipende anche dalle regole per i conflitti. La versione del JDK che esegue il tool non coincide necessariamente con il livello di bytecode prodotto per la distribuzione.',
'Leggi coordinate, versione e ambito della dipendenza. Una libreria di test non è automaticamente nell’app distribuita. Il wrapper fissa la versione del tool tra sviluppatori e CI, ma restano da verificare plugin, SDK e runtime. Una build riproducibile richiede questi elementi insieme.')
guide('java-numbers', 'Per il denaro occorre decidere precisione, scala e arrotondamento secondo regole esplicite.',
'double usa rappresentazione binaria e non descrive esattamente ogni decimale comune. BigDecimal lavora con numeri decimali, ma richiede costruzione e operazioni corrette. Da un double puoi importare un’approssimazione; una stringa descrive direttamente il decimale. equals considera anche la scala, mentre compareTo confronta il valore numerico.',
'Segui la costruzione prima dell’operazione. Per una divisione non terminante scegli precisione o scala e rounding mode. Non cambiare arrotondamento finché l’eccezione scompare: collega la scelta al dominio. Nei confronti chiediti se ti interessi stesso valore o anche stessa scala.')
guide('java-network', 'La rete introduce un confine che può fallire anche con codice e server corretti.',
'Un client prepara metodo, URL, intestazioni e corpo. Riceve poi status e contenuto. Un errore di trasporto è diverso da una risposta HTTP con status di errore. I timeout limitano attese in fasi specifiche. Un retry può ripetere un’operazione già eseguita quando soltanto la risposta è andata persa.',
'Identifica costruzione, invio e lettura della risposta. Controlla lo status prima di deserializzare come successo. Prima di ripetere considera idempotenza, tentativi massimi e ritardo. Il caso peggiore non è solo “non funziona”, ma “eseguito due volte senza saperlo”.')

# Each Spring bridge explains a distinct mechanism, not a generic introduction repeated everywhere.
guide('spring-boot', 'Spring è il framework; Boot aiuta ad avviarlo e configurarlo con convenzioni e integrazioni.',
'Uno starter raggruppa dipendenze; l’auto-configurazione valuta librerie, proprietà e bean presenti. Non è magia fuori dal controllo: una configurazione esplicita può cambiare ciò che viene creato automaticamente. Per capire un avvio cerca condizioni e componenti, non soltanto il nome dell’annotazione.',
'Segui main, classe di avvio e package scansionati. Per un bean mancante controlla dipendenze e condizioni. Per uno esplicito verifica come cambia l’auto-configurazione: Boot non deve creare sempre un secondo componente equivalente.')
guide('spring-di', 'Una dipendenza è un collaboratore necessario a un componente per svolgere il proprio lavoro.',
'Con DI il componente dichiara ciò che gli serve e riceve oggetti dal container, invece di mescolare uso e costruzione. IoC descrive questo spostamento di responsabilità. Il costruttore rende visibili requisiti obbligatori e permette test con collaboratori controllati.',
'Leggi i parametri come requisiti del servizio. Spring cerca bean compatibili e lo costruisce. final protegge la riassegnazione del riferimento, non la mutabilità del collaboratore. Se le dipendenze crescono troppo, verifica se il servizio abbia ancora una responsabilità chiara.')
guide('spring-beans', 'Un bean è gestito dal container; un normale new non registra automaticamente l’oggetto.',
'Component scan rileva tipi nei package previsti; @Bean costruisce esplicitamente oggetti anche esterni al progetto. Più candidati compatibili richiedono una scelta: Qualifier la rende mirata e Primary esprime una preferenza. Registrazione e iniezione sono due passi da riconoscere separatamente.',
'Trova prima il punto di registrazione e poi la dipendenza. Verifica package e selezione del candidato. Un’ambiguità non si risolve correttamente rendendo tutto static: serve capire quale implementazione il chiamante debba ricevere.')
guide('spring-scope', 'Il container decide numero e disponibilità delle istanze, non solo come costruirle.',
'Singleton significa normalmente una istanza per definizione nel container. Campi mutabili possono quindi essere condivisi da richieste concorrenti. Prototype crea istanze quando il container lo risolve, non spontaneamente a ogni metodo di un singleton. Il ciclo di vita delle risorse richiede inoltre un proprietario.',
'Nel servizio distingue dipendenze da dati della singola richiesta. Un prototype iniettato nel costruttore del singleton viene risolto in quel momento; per nuove istanze successive serve una strategia esplicita. Un bean non è thread-safe per il solo fatto di essere gestito.')
guide('spring-config', 'Il codice definisce comportamento; la configurazione fornisce valori diversi tra ambienti.',
'Proprietà, ambiente e argomenti partecipano con precedenze precise. Un profilo attiva configurazioni ma non è una misura di sicurezza. ConfigurationProperties raccoglie valori correlati in un tipo e permette requisiti leggibili e validazione.',
'Collega prefisso, nomi e tipi. Se un valore viene ignorato, cerca chi lo sovrascrive invece di duplicarlo. Segreti non devono essere costanti committate o log. Verifica configurazione all’avvio, prima che un errore emerga durante una richiesta.')
guide('spring-mvc', 'Una richiesta HTTP attraversa infrastruttura prima di raggiungere il metodo del controller.',
'Nel modello Servlet partecipano filtri, DispatcherServlet e adattatori. Vengono individuati handler, preparati argomenti e convertiti corpi. Il controller coordina richiesta e risposta, il servizio gestisce regole e il repository accesso ai dati. Separarli rende più chiara anche la causa degli errori.',
'Segui URL e verbo verso mapping, binding, servizio e risposta. Un errore nel binding può precedere il controller; uno di dominio nasce dopo. Se il breakpoint non viene raggiunto, controlla anche filtri di sicurezza e mapping.')
guide('spring-http', 'HTTP offre metodi e status con significati; REST organizza risorse e interazioni.',
'GET legge, POST invia un’operazione o crea secondo contratto, PUT sostituisce secondo il contratto e PATCH modifica parzialmente. Idempotenza riguarda l’effetto previsto della ripetizione, non risposte identiche. Lo status deve aiutare il client a distinguere esiti senza interpretare ogni corpo come successo.',
'Identifica la risorsa prima del verbo. Una creazione può usare 201 e indicare la risorsa. Distingui identificatore assente da input invalido. Non restituire sempre 200 con error nel JSON: rendi coerenti corpo e semantica HTTP.')
guide('spring-dto', 'Persistenza e contratto pubblico dell’API sono responsabilità diverse.',
'Il DTO sceglie campi, forma e validazioni senza esporre ogni dettaglio della entity. Binding trasforma richiesta in oggetti; serializzazione produce una rappresentazione come JSON. Questa separazione aiuta a controllare relazioni lazy, cicli e campi sensibili, ma non sostituisce autorizzazione.',
'Segui DTO in ingresso, servizio e DTO in uscita. Un ID proprietario inviato dal client non prova un permesso. Valuta quali campi accettare e quali derivare dall’identità autenticata, evitando aggiornamenti involontari dello stato interno.')
guide('spring-validation', 'Un dato può avere forma valida e violare comunque una regola applicativa.',
'Bean Validation applica vincoli dichiarati quando la validazione è attivata. Regole come disponibilità di una prenotazione richiedono contesto nel servizio. Validazione, autorizzazione e vincoli del database sono complementari. Un controllo preliminare può anche essere superato da aggiornamenti concorrenti.',
'Trova @Valid e i campi annotati. Per figli annidati controlla la cascata di validazione. Se la regola dipende da altri dati, identifica transazione e vincolo necessari: il fatto che il DTO sia valido non garantisce che l’operazione sia consentita.')
guide('spring-errors', 'Il client deve riconoscere input invalido, risorsa assente e guasto interno attraverso un contratto stabile.',
'ControllerAdvice traduce eccezioni MVC in risposte coerenti. Il corpo deve essere utile senza esporre stack trace o segreti. Un filtro di sicurezza può però concludere la richiesta prima di quel livello: non tutte le eccezioni passano dallo stesso gestore.',
'Collega eccezione, status e corpo. Errori dei campi possono richiedere dettagli; un guasto interno richiede messaggio pubblico sobrio e log diagnostico. Conserva la causa nella traduzione, così il debugging mantiene l’origine invece di vedere solo l’ultima eccezione.')
guide('spring-jpa', 'JPA è un contratto di persistenza; Hibernate lo implementa. Una entity ha anche un ciclo di vita.',
'Il persistence context coordina oggetti managed e identità. Un nuovo oggetto può essere transient; un oggetto non più associato è detached. Il database conserva righe mentre il contesto gestisce oggetti durante una unità di lavoro. Questi stati determinano quali modifiche possano essere sincronizzate automaticamente.',
'Identifica entity, ID e operazione che produce l’istanza. Poi chiediti se sia managed nella transazione. merge copia stato in un’istanza gestita e restituisce quella istanza: non rende automaticamente managed proprio l’oggetto passato. Usa il risultato secondo il contratto.')
guide('spring-repositories', 'Il repository accede ai dati; il servizio decide scopo, permessi e confine del lavoro.',
'Spring Data interpreta nomi di proprietà e condizioni per derived query. Non è SQL scritto nel nome. Query esplicite e proiezioni possono soddisfare casi più precisi. La comodità dell’API non annulla costo, cardinalità o autorizzazione.',
'Nel nome del metodo segui proprietà reali e relazioni annidate. Verifica il ritorno: una query potenzialmente multipla non dovrebbe promettere un singolo valore senza regola. Per performance controlla SQL e dati letti, non solo la brevità del metodo.')
guide('spring-relations', 'I collegamenti tra oggetti devono diventare colonne, chiavi esterne o tabelle di associazione.',
'Due proprietà di una relazione bidirezionale non descrivono necessariamente due collegamenti separati. Il lato proprietario determina gli aggiornamenti secondo il mapping; mappedBy indica sul lato inverso quale proprietà li governa. Coerenza in memoria e scrittura nel database sono entrambe necessarie.',
'Trova la FK e il lato proprietario. Aggiornare soltanto la collezione inversa può non salvare il collegamento atteso. Un helper può aggiornare riferimento del figlio e collezione del genitore, mantenendo entrambi coerenti senza cambiare ownership.')
guide('spring-fetch', 'Caricare una entity non significa caricare immediatamente ogni relazione raggiungibile.',
'Lazy loading rinvia un caricamento entro le condizioni del contesto. N+1 descrive una query iniziale seguita da molte aggiuntive, spesso una per elemento visualizzato. Un fetch plan sceglie dati per il caso d’uso. Rendere tutto EAGER non elimina necessariamente costo o query aggiuntive.',
'Segui query iniziale e accessi alle relazioni nel ciclo. Conta SQL reale. Proiezione o fetch mirato possono evitare attraversamenti. Dopo chiusura del contesto non aspettare la serializzazione JSON per scoprire una relazione lazy non caricabile.')
guide('spring-cascade', 'Relazione, ownership e propagazione delle operazioni sono scelte differenti.',
'Cascade propaga operazioni di persistenza e non equivale a ON DELETE CASCADE del database. orphanRemoval riguarda figli il cui ciclo di vita dipende dalla relazione col genitore. Prima di aggiungere REMOVE chiediti se il figlio possa essere indipendente o condiviso.',
'Distingui cancellazione del genitore e rimozione dalla collezione. Simula entrambi e verifica SQL e dati rimasti. Non aggiungere cascata soltanto per eliminare un errore di salvataggio: deve rappresentare la responsabilità reale sul ciclo di vita.')
guide('spring-dirty', 'Il dirty checking riguarda modifiche a una entity managed nel persistence context.',
'Hibernate può rilevare cambiamenti e prepararne l’aggiornamento senza save esplicito a ogni setter. Flush sincronizza attraverso SQL; commit conferma la transazione. Sono passaggi distinti: SQL inviato durante flush può ancora appartenere a una transazione poi annullata.',
'Nel metodo transazionale segui lettura, modifica, flush e conclusione. Se l’istanza è detached, non applicare automaticamente la stessa regola. Osserva SQL ed esito della transazione: la presenza o assenza di save da sola non spiega il comportamento.')
guide('spring-transactions', 'Un confine transazionale collega operazioni che devono avere un esito coerente.',
'Spring può intercettare la chiamata tramite proxy e gestire commit o rollback. Nella configurazione usuale RuntimeException ed Error causano rollback; checked exception richiedono regole esplicite se necessario. Un’annotazione non rende transazionali anche effetti remoti che il database non può annullare.',
'Identifica il chiamante esterno al proxy. Self-invocation può saltare l’intercettazione. Se catturi un errore e ritorni normalmente, non assumere un rollback automatico. Verifica quali operazioni siano davvero nel confine e quali restino effetti esterni.')
guide('spring-propagation', 'Dopo una transazione singola, considera una chiamata transazionale dentro un’altra.',
'Propagation decide la partecipazione: REQUIRED usa quella esistente o ne crea una; REQUIRES_NEW apre un confine indipendente secondo il supporto del manager. Isolation riguarda ciò che operazioni concorrenti possono osservare. Sono dimensioni distinte, da scegliere per un problema identificato.',
'Disegna chiamante, chiamato e query. Un commit indipendente può restare confermato dopo rollback esterno. Considera anche connessioni aggiuntive e pool. Prima dell’isolamento identifica l’anomalia concreta e le garanzie del database, invece di scegliere sempre il livello più forte.')
guide('spring-locking', 'Due richieste possono leggere lo stesso stato e aggiornare senza conoscere la modifica reciproca.',
'@Version permette locking ottimistico: l’aggiornamento considera la versione attesa e rileva conflitti. Non blocca una riga durante tutta l’attesa dell’utente. Il locking pessimistico coordina tramite lock del database, con attese e possibili deadlock. La scelta dipende dal conflitto da gestire.',
'Simula due letture della versione 3. La prima scrive versione 4; la seconda basata su 3 deve gestire il conflitto invece di sovrascrivere. Ricaricare o ripetere un’operazione idempotente sono opzioni da valutare. Un retry cieco può violare la scelta originale dell’utente.')
guide('spring-pagination', 'Un risultato grande non deve essere sempre caricato interamente per mostrarne una porzione.',
'Page include informazioni sul totale e può richiedere conteggio; Slice indica una porzione successiva senza lo stesso totale globale. Un ordine stabile evita spostamenti arbitrari tra righe con valori uguali. Dimensione richiesta e costo della query restano responsabilità applicative.',
'Controlla indice di pagina, dimensione e sort. Aggiungi un ID come spareggio quando utile. Limita richieste del client e osserva anche la query di conteggio. Un offset molto grande può essere costoso pur essendo formalmente valido.')
guide('spring-security-chain', 'Autenticazione ricostruisce identità; autorizzazione decide le azioni consentite.',
'La catena di filtri precede il controller. Filtri possono estrarre credenziali, richiedere autenticazione e applicare accesso. AuthenticationManager coordina provider; SecurityContext conserva il risultato secondo la strategia. Una catena configurata non equivale a un login completo funzionante.',
'Segui credenziali, verifica, contesto e permesso. Un Resource Server JWT richiede decoder adeguato. Se il controller non parte, individua filtro o regola che ha risposto, distinguendo quel rifiuto da un errore nella logica del servizio.')
guide('spring-passwords', 'Verificare una password non richiede conservarne una copia leggibile.',
'PasswordEncoder applica un algoritmo adatto e verifica con matches. Non è cifratura da decodificare. Sale e costo ostacolano attacchi su valori memorizzati. Il login richiede anche limiti ai tentativi e messaggi che non rivelino inutilmente gli account esistenti.',
'encode serve al salvataggio; matches confronta proposta e valore conservato. Non confrontare due encode aspettandoti stringhe identiche. Verifica costo adeguato e gestione di credenziali errate. Password e token non devono comparire nei log diagnostici.')
guide('spring-authorization', 'Un utente riconosciuto può comunque non avere accesso a una particolare risorsa.',
'Ruoli e authority esprimono permessi secondo un contratto. Ownership verifica appartenenza o una regola esplicita. Method security colloca controlli vicino alle operazioni, ma richiede attivazione ed intercettazione. Il solo login non autorizza a cambiare ID per vedere dati altrui.',
'Distingui ruolo e controllo sulla risorsa. Per hasRole considera il prefisso atteso; hasAuthority confronta l’authority effettiva. Verifica almeno proprietario, altro utente e amministratore secondo le regole del servizio, senza affidarti al solo filtro HTTP.')
guide('spring-jwt', 'Il token è una credenziale e va verificato prima di fidarsi del contenuto.',
'Un JWT firmato ha header, payload e firma. La firma protegge integrità secondo algoritmo e chiave, ma non cifra il payload. Resource Server verifica il token; emetterlo è una responsabilità distinta. Decodificare JSON non prova validità: servono controlli di firma, scadenza, issuer e audience previsti dal contratto.',
'Trova emittente, chiave e decoder. Segui poi claim verso authority. Token valido non significa permesso su ogni risorsa. Non inserire password o dati segreti nel payload. Prova token scaduto o con destinatario errato oltre al caso valido.')
guide('spring-refresh', 'Access token breve e continuità della sessione richiedono una strategia di rinnovo.',
'Il refresh token consente nuove credenziali con un contratto distinto. Rotazione sostituisce quello usato e deve gestire riutilizzo. Eliminare il cookie non revoca magicamente access token già emessi. HttpOnly limita lettura JavaScript, ma non risolve da solo CSRF e autorizzazione.',
'Segui login, accesso, refresh e nuova coppia. Considera due richieste concorrenti con stesso refresh. Verifica Secure, SameSite, path e durata rispetto al deployment. Il logout deve esprimere quali credenziali invalida e quali restano valide fino a scadenza.')
guide('spring-csrf', 'Invio automatico di credenziali e lettura cross-origin sono questioni diverse del browser.',
'CSRF sfrutta richieste indesiderate con credenziali inviate automaticamente, come cookie. CORS regola accesso cross-origin nel browser e non è autorizzazione generale del server. Una API soltanto bearer può avere una scelta CSRF diversa da un endpoint autenticato con cookie.',
'Identifica credenziali di ogni endpoint, incluso refresh. Configura origini, metodi e header senza interpretare preflight come identità. Non disabilitare protezioni copiando un esempio: collega la scelta al modo in cui il browser invia le credenziali.')
guide('spring-security-errors', 'Identità non valida e permesso negato a un’identità valida sono casi distinti.',
'401 indica normalmente necessità di autenticazione valida; 403 rifiuto dell’accesso. Entry point e access denied handler intervengono nei filtri; ControllerAdvice riguarda MVC. Un contratto può scegliere di nascondere l’esistenza di risorse, ma la decisione deve essere coerente e verificata.',
'Prova senza credenziali, con credenziali invalide, con permesso insufficiente e con proprietario valido. Verifica status e corpo. Non concludere che la protezione funzioni dal solo caso positivo e mantieni log utili senza esporre credenziali.')
guide('spring-tests', 'Usa il confine più piccolo che dimostra davvero il comportamento richiesto.',
'Un test unitario può creare il servizio senza Spring. Slice carica componenti mirati; SpringBootTest coinvolge un contesto più ampio. MockMvc esercita MVC senza necessariamente avviare un server esterno. Un repository mockato non verifica SQL, e un caso autorizzato non verifica i rifiuti.',
'Identifica ciò che viene caricato e sostituito. Per persistenza controlla dati iniziali e database reale di riferimento. Per sicurezza aggiungi casi negati. Non rendere il test più grande soltanto per usare una annotazione: deve aumentare l’evidenza utile.')
guide('spring-migrations', 'Una modifica alla entity non aggiorna in sicurezza da sola un database già popolato.',
'Una migrazione descrive un cambiamento ordinato di schema o dati. Flyway conserva cronologia e controlla script. Uno script già applicato non va riscritto per nascondere una nuova modifica: aggiungi un passo. Considera anche compatibilità di codice e schema durante il rilascio.',
'Simula la tabella popolata prima di aggiungere NOT NULL o un vincolo. Può servire un riempimento preliminare. Prova database vuoto e aggiornamento dalla versione precedente. Non confondere uno schema ricreato senza dati con una migrazione riuscita.')
guide('spring-actuator', 'Un processo avviato non dimostra che ogni flusso applicativo sia sano.',
'Actuator espone strumenti operativi; metriche aggregano fenomeni e log descrivono eventi. Health riguarda controlli configurati e non prova ogni caso d’uso. Gli endpoint operativi devono essere esposti e protetti consapevolmente, perché possono rivelare informazioni sul sistema.',
'Controlla endpoint e destinatari. Evita ID utente come etichette metriche ad alta cardinalità. Collega errori a richieste con correlazione senza token nei log. Scegli segnali che permettano di riconoscere un guasto e prendere una decisione.')
guide('spring-cache', 'La cache conserva risultati per evitare letture o calcoli ripetuti.',
'La copia può diventare obsoleta: invalidazione e consistenza sono parte del progetto. Cacheable riusa per chiave e CacheEvict invalida secondo contratto. Redis fornisce una risorsa esterna, ma non sceglie da solo chiavi, durata o permessi. Il beneficio dipende anche dal tasso di riuso.',
'Segui prima lettura, poi ripetizione, poi modifica. Quale chiave viene invalidata? Se il risultato dipende dall’utente, il solo ID risorsa può non bastare. Considera indisponibilità della cache e comportamento atteso, evitando di trasformarla in fonte unica accidentale.')
guide('spring-async', 'Prima comprendi executor: una annotazione si collega a quei meccanismi e non elimina i limiti.',
'Una chiamata @Async intercettata può consegnare lavoro a un executor e restituire controllo. Self-invocation può evitare il proxy. Transazione e contesti del thread non si trasferiscono automaticamente. Lavori in memoria possono essere persi con l’arresto del processo.',
'Identifica chiamata esterna, executor, coda e gestione errori. Per void il chiamante non riceve un Future di fallimento. Scheduling pianifica, ma più istanze possono eseguire lo stesso lavoro: non è coordinamento distribuito né consegna persistente automatica.')
guide('spring-events', 'L’evento comunica un fatto; il listener sceglie come reagire.',
'Separare pubblicazione e reazione riduce accoppiamento, ma non garantisce asincronia o persistenza. Un evento transazionale richiede una scelta sul momento della reazione. Pubblicare un evento prima del commit non dimostra che il dato sarà confermato.',
'Segui modifica, pubblicazione e listener. AFTER_COMMIT evita alcuni effetti per transazioni annullate, ma un crash può ancora avvenire prima della reazione completa. Per affidabilità oltre il processo valuta persistenza come outbox e consumatori idempotenti.')
guide('spring-webclient', 'Una chiamata remota può essere lenta, fallire o tornare con una risposta inattesa.',
'Il client gestisce status, corpo e timeout. WebClient offre un modello reattivo, ma non rende ogni dipendenza non bloccante. Retry richiede limite e valutazione degli effetti ripetuti. Circuit breaker limita chiamate verso un servizio in guasto secondo una politica, non ripara il servizio.',
'Distingui costruzione e consumo del risultato. Controlla status prima del DTO. Se usi block, identifica il thread e non bloccare un event loop. Una creazione ripetuta dopo perdita di risposta può duplicare l’effetto: considera chiavi di idempotenza dove previste.')
guide('spring-deployment', 'Collega codice e artefatto mediante build riproducibile e configurazione esplicita.',
'Il jar Boot può includere server e dipendenze. Il container definisce un ambiente ma non rende corretti segreti, migrazioni e limiti. Un rilascio richiede disponibilità, osservabilità e terminazione ordinata. Il runtime destinatario deve comprendere il bytecode prodotto.',
'Verifica versione Java, utente di esecuzione e configurazione esterna. Controlla health e tempo di shutdown. Un container avviato ma incapace di raggiungere il database non è una prova di rilascio riuscito. Prova il flusso applicativo essenziale.')
guide('spring-reactive', 'Prima comprendi thread, HTTP e attesa I/O: reattivo non significa semplicemente più moderno.',
'MVC usa Servlet; WebFlux espone Publisher che producono segnali secondo sottoscrizione. Mono descrive zero o un elemento, Flux una sequenza. Backpressure esprime domanda dal consumatore, ma restano da controllare buffer e risorse. Il vantaggio dipende dalla catena e dal carico.',
'Il controller restituisce una descrizione consumata dall’infrastruttura. JDBC dentro Mono resta bloccante. block su event loop può fermare altri lavori. Scegli WebFlux quando dipendenze e problema lo giustificano; per molti servizi MVC resta coerente.')

def apply_guides(topics):
    assert {topic['id'] for topic in topics} == set(GUIDES), 'Every lesson needs its own bridge'
    for topic in topics:
        prerequisite, bridge, trace = GUIDES[topic['id']]
        original = topic['explanation'].split('\n\nPunti da verificare\n', 1)[0]
        topic['explanation'] = ('## Prima di iniziare\n\n' + prerequisite +
            '\n\n## Costruiamo il concetto\n\n' + bridge +
            '\n\n## Il meccanismo in dettaglio\n\n' + original +
            '\n\n## Leggiamo l’esempio passo per passo\n\n' + trace)
